# Lot 2 : §3 (C5), §4, §5, §6, §7 (C4/C5/C6/C7/C8) + observations O3-O7.
import re,sys
p='HYLO-ET-AUTRES-CHAINES.md'
t=open(p).read()
# --- remplacement du tableau §3.1 et des §3.2, §3.3 (de l'en-tête du tableau jusqu'à la ligne '---' qui précède §4)
i=t.index('| Date | Chaîne / protocole |')
j=t.index('## 4. Synthèse transversale')
new_block='''| Date | Chaîne / protocole | Ce qui s'est passé (lu) | Montant | Source (copie), niveau | Confiance | Type |
|---|---|---|---|---|---|---|
| **avant le 2024-04-19** (article publié le 2024-04-19, modifié le 2024-05-21 ; date de l'incident non donnée) | Solana, MarginFi | Liquidations massives de positions LST après des changements d'oracle et des décrochages de LST ; remboursements par le fonds d'assurance ; “MarginFi had recently made changes to its Oracle system” ; le protocole s'exprime “3 days after the incident” | remboursement intégral sous un seuil de 10 à 20 k$ de compte, compensation pour moins de dix gros comptes | `inc-marginfi-refund.txt` (SolanaFloor ; date lue dans la métadonnée `article:published_time` de `inc-marginfi-refund.raw`) [2nd] | moyenne (un article ; aucun rapport du protocole lu) | changement de configuration d'oracle pendant la congestion, avec décrochage de LST ; la source ne décrit aucune divergence entre places |
| **2025-03-26** | Hyperliquid, JELLY | Selon CoinDesk, d'après Lookonchain, un trader aurait (“allegedly manipulated”) le prix du jeton sur des places spot minces ; Hyperliquid a fermé le marché en le réglant à 0,0095 $ “as opposed to $0.50 that was being fed to oracles via decentralized exchanges” ; “the validator set convened and voted to delist JELLY perps” | HLP : perte latente de 13,5 M$ à un moment donné | `inc-hl-jelly-coindesk.txt` (CoinDesk, 2025-03-26, mise à jour 03-27) [2nd] | moyenne | marché mince, oracle alimenté par des DEX |
| **2025-04-26** | Solana, Loopscale | Faille de validation du programme de prix des jetons PT de RateX : un programme falsifié renvoyait un taux gonflé ; Loopscale combine ce prix avec “Pyth oracle feeds” | 5 726 725 USDC + 1 211,4 SOL, **tout récupéré** | `inc-loopscale.txt` (blog Loopscale, post-mortem) [lu] | élevée | validation de programme manquante (prix obtenu par appel de programme non validé) |
| **2025-10-10** | Base, Moonwell | Krach de marché ; “oracles were quoting significantly lower prices than DEXs, potentially due to heavy reliance on Binance data” (hypothèse du rapport) ; l'attaquant a emprunté VIRTUAL, MORPHO, AERO avec cbBTC/USDC en garantie ; les liquidateurs n'ont pas pu sortir, le bonus de 7 % étant dépassé par des écarts oracle/DEX de 20–30 % | ≈ 1,7 M$ de mauvaise dette | `inc-moonwell-1983.json` (Anthias Labs, 2025-10-17) [lu] | élevée pour les faits on-chain ; la cause « Binance » est une hypothèse du rapport | divergence oracle/DEX en stress |
| **2025-11-04** | Base, Moonwell | Le flux Chainlink wrsETH/ETH a renvoyé “1 wrsETH equals 1,649,934.60732 ETH” (le rapport écrit que le flux “erroneously reported”) ; attaque exécutée en 30 s | 3,7 M$ de mauvaise dette | `inc-moonwell-2017.json` (Anthias Labs) [lu] | élevée | flux erroné, composé avec le flux ETH/USD |
| **2025-11-12** | Hyperliquid, POPCAT | “Hyperliquid paused deposits and withdrawals after a trader’s $3M POPCAT bet caused $25M in liquidations and a $4.9M HLP loss.” ; la source parle de “what appeared to be a deliberate attempt” de manipulation ; verrou du pont Arbitrum levé après ≈ 25 min. **La source ne mentionne aucun oracle** : le lien avec l'oracle de prix est **[inféré]** | HLP : 4,9 M$ | `inc-hl-popcat.txt` (The Crypto Times, 2025-11-13) [2nd] | moyenne pour l'événement ; lien avec l'oracle non établi | manipulation du carnet sur un actif mince |
| **2026-02-15** | Base/Optimism, Moonwell | Déploiement des enveloppes OEV (MIP-X43) : “the oracle used only the raw cbETH/ETH exchange rate” : cbETH valorisé ≈ 1,12 $ au lieu de ≈ 2 200 $ ; 1 096 cbETH saisis | 1,78 M$ de mauvaise dette ; ≈ 2,68 M$ de pertes nettes pour ≈ 181 emprunteurs (fil 2084) | `inc-moonwell-2068.json` ; `inc-moonwell-2084.json` [lu] | élevée | erreur de configuration |
| **2026-04-01** | Solana, Drift | Compromission des clés d'un comité de sécurité (ingénierie sociale, nonces durables), puis listing d'un faux jeton CVT comme garantie : “deploying a price oracle they controlled to feed that artificial price to Drift” (Chainalysis). Nexus Mutual : “The oracle manipulation was a downstream effect of the key compromise, not an independent failure of Drift's oracle system.” | ≈ 285 M$ | `inc-drift-chainalysis.txt` (2026-04-09), `inc-drift-nexus.txt` (2026-04-09) [2nd] ; post-mortem de Drift **[abs]** | moyenne (deux analystes concordants ; Chainalysis note que le post-mortem de Drift n'est pas vérifié par un tiers) | clé compromise ; oracle sous contrôle de l'attaquant |
| **2026-04-26** | Sui, Scallop | Selon un article de presse : “The attacker used a flash loan to manipulate Scallop's oracle price feeds” ; l'article n'est pas étayé par un rapport du protocole | 142 k$ (article) | `inc-sui-scallop.txt` (Startup Fortune, 2026-04-26) [2nd] | faible (article généraliste, détails non recoupés) | manipulation (non confirmée) |
| **2026-08-27** | Base, Moonwell (marché MAMO) | Dons directs de MAMO au contrat (taux d'échange ×3,68) et achats sur DEX peu profonds : “the MAMO/USD source feed rose from approximately $0.010597 to $0.43127363” ; 18 emprunts | 11,03 M$ empruntés ; ≈ 9,1 M$ de dette résiduelle estimée | `inc-moonwell-2208.json` (Anthias Labs, 2026-08-28) [lu] | élevée pour les faits on-chain ; la dette résiduelle est une estimation du rapport | manipulation de marché mince + comptabilité du collatéral |
| **2026-08-28** | Switchboard (implémentation Move) : **IOTA** (exploitation documentée), **Sui** (compromission “suspected” selon Full Sail), **Aptos et Movement** (suspension par précaution) | “an attacker exploited a defect in the attestation logic of Switchboard's Move-language oracle implementation to install a signing key they controlled” sur les quatorze oracles de la file IOTA ; prix soumis jusqu'à 10 000 000 $ par IOTA, puis proches de zéro. Deux défauts combinés : création de gardien sans autorisation, et comparaison de clé vide qui renvoie vrai. Défaut présent depuis la première version publique (août 2025). “No keys were extracted and no infrastructure was breached.” Les quatre déploiements Move sont suspendus, y compris sur des chaînes sans incident signalé. Le post-mortem écrit : “We have received no reports of similar behavior on Solana.” ; Solana Compass écrit que les flux Solana n'étaient pas affectés “at that time” | **Virtue (IOTA)** : “The attacker minted 4,942,737.62 VUSD against 1.027 IOTA of collateral, reducing protocol-wide backing to 8.0%.” ; **Full Sail (Sui)** : “A loss of funds has been confirmed.” (≈ 91 k$ selon un tiers [2nd]) | `inc-switchboard-postmortem.txt` (page datée 2026-09-18 par sa métadonnée `article:published_time`) [lu] ; `x-virtue-incident-report.txt` (2026-08-30) [lu] ; `x-fullsail-2026-08-29.txt` [lu] ; `inc-sui-shattered.txt` (publiée le 2026-09-10) [2nd] | élevée pour IOTA et Virtue ; moyenne pour Sui ; faible pour le montant de Full Sail | défaut d'attestation (oracle) sur IOTA ; suspension de précaution ailleurs |
| **2026-09-18 / 2026-09-19** | Switchboard, toutes chaînes | Le profil X de la fondation épingle “An update: Switchboard is shutting down.” (titre et extrait seulement, 2026-09-18). Solana Compass (2026-09-19) : “all implementations are deprecated effective immediately, with all support services ending on September 25” ; intégrateurs cités : Kamino, Jito, MarginFi, Drift. La même source présente la fermeture comme “a separate decision from that incident” : **aucun lien causal avec l'exploitation d'août** n'est établi par les copies. L'arrêt effectif n'est pas lu **[abs]** | n/a | `x-switchboardfdn-profile.txt` [lu, titre et extrait] ; `inc-switchboard-shutdown.txt` [2nd] | moyenne (une source de presse ; titre primaire partiel) | sortie d'un fournisseur |

Le post-mortem de Switchboard dit aussi que, pour les chaînes concernées, “There is no guarantee of future support and any remediation is dependent on new contributors” (`inc-switchboard-postmortem.txt`) [lu].

### 3.2 Constats sur les sources elles-mêmes
- **Le post-mortem de Switchboard et la presse ne disent pas la même chose** : Solana Compass parle d'une “suspected key compromise” ; le post-mortem primaire affirme qu'aucune clé n'a été extraite (voir tableau) : c'est le défaut d'attestation. J'ai retenu la version primaire pour IOTA [lu].
- Un seul incident de 2023–2024 est daté : MarginFi (article du 2024-04-19). **Ma liste n'est donc pas exhaustive** pour 2023–2024 **[abs]**.

### 3.3 Ce que ces incidents montrent pour Shōgen **[inféré]**

1. **Sept familles de causes**, alignées sur le tableau : divergence entre prix d'oracle et prix de DEX en stress (Moonwell 2025-10-10) ; flux erroné (wrsETH/ETH) ; configuration (cbETH ; MarginFi, changement de configuration d'oracle pendant la congestion avec décrochage de LST) ; validation de programme manquante (Loopscale) ; clé ou attestation (Drift, Switchboard) ; marché mince (JELLY, MAMO ; POPCAT et Scallop sous réserve des sources) ; sortie du fournisseur (Switchboard, sans lien causal établi avec l'exploitation). Shōgen mesure une relation entre sources (racines communes), pas une panne de configuration ni une clé compromise : seule la première famille touche à une relation entre prix de sources, et la source de MarginFi ne décrit aucune divergence entre places.
2. **Parmi les incidents lus, aucun ne porte sur BTC, ETH, USDC ou USDT** comme actif dont le prix a été faussé ; les prix faussés concernent des actifs de moyenne ou longue traîne (JELLY, POPCAT, VIRTUAL, MORPHO, AERO, MAMO, wrsETH, cbETH, IOTA, ou le jeton CVT de Drift). S2-bis, tel que défini, n'aurait pas produit de signal sur ces événements. Le seul lien est indirect : la nature de la **chaîne de valorisation** (wrsETH = flux wrsETH/ETH × flux ETH/USD ; cbETH = ratio × ETH/USD) est ce que `SYNTHESE-CROISEMENT.md` (ligne 245) prévoit déjà de documenter par une arête de type racine unique rattachée au contrat.
3. **La concentration sur un fournisseur est le risque le plus clairement observé** : le même défaut d'attestation de Switchboard a conduit à suspendre quatre déploiements (IOTA avec exploitation documentée, Sui avec compromission “suspected” selon Full Sail), et le fournisseur a annoncé séparément sa fermeture (les copies n'établissent aucun lien causal). Une carte R2 qui répertorie, par protocole, quelles racines alimentent quel flux, datée, aurait montré 4 piles sur 11 (§4) qui nomment ce fournisseur **avant** l'événement. C'est l'apport le plus concret et le plus facile à établir à partir de sources publiques.
4. **Les réponses documentées passent par des plafonds et des pauses** (plafonds de cbETH ramenés à 0,01 chez Moonwell, gel du protocole chez Virtue, dépôts et retraits suspendus chez Full Sail) plutôt que par un recoupement de sources ; Virtue écrit après coup : “The incident exposed an additional defense-in-depth requirement around price magnitude and source independence” (`x-virtue-incident-report.txt`) [lu] ; son correctif : “All four aggregaters now use Pyth, CertRule or VCertRule only; none reads Switchboard.” [lu].
5. **Latence de gouvernance** : sur Moonwell, une correction d'oracle exige 5 jours de vote et de timelock ; les liquidations continuent pendant ce temps (incident cbETH) [lu].

---

'''
t=t[:i]+new_block+t[j:]
R=[]
def r(a,b): R.append((a,b))
# §2.7
r("cette page cite Switchboard alors que Switchboard a suspendu ses déploiements Move le 2026-08-29 et annoncé sa fermeture au 2026-09-25 (§3.1).","cette page cite Switchboard alors que Switchboard a suspendu ses déploiements Move le 2026-08-29 et que Solana Compass annonce la fin des services de support au 2026-09-25 [2nd] (§3.1).")
# §4
r("alors que ses déploiements Move sont suspendus depuis le 2026-08-29 et le service arrêté le 2026-09-25 [lu pour les pages ; inféré pour les totaux].","alors que ses déploiements Move sont suspendus depuis le 2026-08-29 (post-mortem) et que la fin des services de support est annoncée pour le 2026-09-25 (Solana Compass [2nd]) [lu pour les pages ; inféré pour les totaux].")
r("(Pythnet supprimé, cinq routeurs,","(Pythnet en cours d'arrêt, cinq routeurs,")
r("- **Les redondances déclarées ne sont pas des racines indépendantes** tant que la liste des places derrière chaque flux n'est pas connue : Kamino (Chainlink + Pyth Pro), Jupiter, Thala, Echelon **[inféré]**.","- **Les redondances déclarées** (Kamino : Chainlink + Pyth Pro ; Jupiter ; Thala ; Echelon) **restent des redondances déclarées** : sans la liste des places derrière chaque flux, aucun recouvrement n'est mesuré **[inféré]**.")
# §5
r("- **OtterSec** : couverture du PDF datée du 5 mai 2025, nom de fichier `…20250513`, doc Hylo écrivant “OtterSec, Feb 2025”. Je cite la couverture [lu].","- **OtterSec** : le PDF date lui-même l'évaluation (“conducted between February 10th and February 27th, 2025”, suivi du 2 au 30 avril 2025) ; la couverture est datée du 5 mai 2025, le nom de fichier porte `…20250513` ; la doc Hylo écrit “OtterSec, Feb 2025” : c'est la période d'évaluation, ce n'est pas un écart [lu].")
r("- **Switchboard** : 18 septembre (profil X) contre 19 septembre (Solana Compass) pour l'annonce ; le profil X ne donne que le titre de l'article, pas son corps [lu].","- **Switchboard** : 18 septembre (profil X) contre 19 septembre (Solana Compass) pour l'annonce ; le profil X montre le titre de l'article et un court extrait, pas son corps [lu]. La date du 2026-09-25 ne vient que de Solana Compass [2nd].\n- **Pyth, mise à niveau du 2026-08-26** : `pyth-upg-contracts.txt` écrit “You kept your address, and your feed IDs didn't change” (sauf sur Sui), alors que `pyth-upg-solana.txt` et la section Solana de la même page annoncent de nouveaux programmes et de nouveaux comptes push par flux. Les deux pages ne disent pas la même chose ; pour Hylo, la conséquence est **[abs]** (la table des comptes est rendue en JavaScript et absente de la copie).")
r("- **Chiffre Full Sail 91 000 $** : tiers uniquement (`inc-sui-shattered.txt`), page non datée, à ne pas reprendre sans source primaire.","- **Chiffre Full Sail 91 000 $** : tiers uniquement (`inc-sui-shattered.txt`, page publiée le 2026-09-10 d'après sa métadonnée `datePublished`), à ne pas reprendre sans source primaire.")
# §6
r("7. **Incidents 2023–2024** sur ces chaînes : non couverts (aucune page datée collectée) ; **ma liste d'incidents n'est pas exhaustive**.","7. **Incidents 2023–2024** sur ces chaînes : seul MarginFi (avril 2024) est daté et couvert ; **ma liste d'incidents n'est pas exhaustive**.")
r("8. **Lecture partielle** : voir l'en-tête (index `*-llms.txt`, fils du forum Moonwell au-delà du premier message, page Chainalysis).","8. **Lecture partielle** : voir l'en-tête (index `*-llms.txt`, fils du forum Moonwell au-delà du premier message, page Chainalysis).\n9. **Provenance des copies** (relecture G2, C8) : `pages2/jup-dev-llms.raw` est une page 404 du portail Jupiter (HTML de 15 162 octets), alors que `pages2/jup-dev-llms.txt` est octet pour octet `pages2/jupx-742488.raw` (index texte de Jupiter, même sha256 `f90a7559…`), qui porte la citation sur les custodies du pool JLP ; **l'URL source de `jupx-742488.raw` n'est pas consignée** ; `pages2/kamino-llms.txt` n'a pas de `.raw` ; les `pages/*.derived.txt` ont été produits sans script consigné (leurs citations figurent dans le HTML reçu).\n10. **URL des copies** : la collecte n'a pas consigné les URL ; `INDEX-COPIES.md` donne celles qui se retrouvent dans les octets des copies ou dans leurs index (127 copies sur 193), et marque les autres « non consignée » (66).")
r("  - `pages2/` : comparables (Aries, Bucket, Drift/Velocity, Echelon, Felix, Hyperliquid, Jupiter, Kamino, Moonwell, NAVI, Suilend, Thala), Pyth (`pyth-*`), incidents (`inc-*`, `x-*`). Les `.raw` sont les octets reçus, les `.txt` leur texte.","  - `pages2/` : comparables (Aries, Bucket, Drift/Velocity, Echelon, Felix, Hyperliquid, Jupiter, Kamino, Moonwell, NAVI, Suilend, Thala), Pyth (`pyth-*`), incidents (`inc-*`, `x-*`). Les `.raw` sont les octets reçus et les `.txt` leur texte, **sauf** les anomalies déclarées au §6 point 9 (`jup-dev-llms`, `kamino-llms`).")
r("  - `quotes.txt` (citations vérifiées de ce rapport), `quotes-v1-premiere-passe.txt`, `chk.py` et les petits scripts de collecte (`fetch.sh`, `ddg.sh`, `bing.sh`).","  - `quotes.txt` (citations contrôlées par `chk.py`), `quotes-v1-premiere-passe.txt`, `chk.py` et les petits scripts de collecte (`fetch.sh`, `ddg.sh`, `bing.sh`).\n  - `INDEX-COPIES.md` (copie → URL), `HYLO-ET-AUTRES-CHAINES.v1-avant-G2.md` (version relue par la G2, sha256 `a24e7cf2…94f65`), `corrections-g2/` (scripts des remplacements du §8).\n  - `g2/` : relecture G2 (lue seulement, jamais modifiée).")
r("  - `SHA256SUMS` : empreintes de tous les fichiers du dossier, **y compris ce rapport** ;","  - `SHA256SUMS` : empreintes de tous les fichiers du dossier **y compris `g2/`**, ce rapport inclus, établies après les corrections du §8 ;")
# observations
r("(l'ordre chronologique est inhabituel mais c'est ce que la page affiche)","(l'ordre chronologique est inhabituel mais c'est ce que la page affiche)")
bad=0
for a,b in R:
    if a not in t: print('INTROUVABLE:',a[:100]); bad+=1
    else: t=t.replace(a,b,1)
if bad: sys.exit('abandon')
open(p,'w').write(t); print('lot 2 appliqué')
